require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProfessionalQuestionsController do

  # This should return the minimal set of attributes required to create a valid
  # ProfessionalQuestion. As you add validations to ProfessionalQuestion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all professional_questions as @professional_questions" do
      professional_question = ProfessionalQuestion.create! valid_attributes
      get :index
      assigns(:professional_questions).should eq([professional_question])
    end
  end

  describe "GET show" do
    it "assigns the requested professional_question as @professional_question" do
      professional_question = ProfessionalQuestion.create! valid_attributes
      get :show, :id => professional_question.id
      assigns(:professional_question).should eq(professional_question)
    end
  end

  describe "GET new" do
    it "assigns a new professional_question as @professional_question" do
      get :new
      assigns(:professional_question).should be_a_new(ProfessionalQuestion)
    end
  end

  describe "GET edit" do
    it "assigns the requested professional_question as @professional_question" do
      professional_question = ProfessionalQuestion.create! valid_attributes
      get :edit, :id => professional_question.id
      assigns(:professional_question).should eq(professional_question)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProfessionalQuestion" do
        expect {
          post :create, :professional_question => valid_attributes
        }.to change(ProfessionalQuestion, :count).by(1)
      end

      it "assigns a newly created professional_question as @professional_question" do
        post :create, :professional_question => valid_attributes
        assigns(:professional_question).should be_a(ProfessionalQuestion)
        assigns(:professional_question).should be_persisted
      end

      it "redirects to the created professional_question" do
        post :create, :professional_question => valid_attributes
        response.should redirect_to(ProfessionalQuestion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved professional_question as @professional_question" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProfessionalQuestion.any_instance.stub(:save).and_return(false)
        post :create, :professional_question => {}
        assigns(:professional_question).should be_a_new(ProfessionalQuestion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProfessionalQuestion.any_instance.stub(:save).and_return(false)
        post :create, :professional_question => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested professional_question" do
        professional_question = ProfessionalQuestion.create! valid_attributes
        # Assuming there are no other professional_questions in the database, this
        # specifies that the ProfessionalQuestion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProfessionalQuestion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => professional_question.id, :professional_question => {'these' => 'params'}
      end

      it "assigns the requested professional_question as @professional_question" do
        professional_question = ProfessionalQuestion.create! valid_attributes
        put :update, :id => professional_question.id, :professional_question => valid_attributes
        assigns(:professional_question).should eq(professional_question)
      end

      it "redirects to the professional_question" do
        professional_question = ProfessionalQuestion.create! valid_attributes
        put :update, :id => professional_question.id, :professional_question => valid_attributes
        response.should redirect_to(professional_question)
      end
    end

    describe "with invalid params" do
      it "assigns the professional_question as @professional_question" do
        professional_question = ProfessionalQuestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProfessionalQuestion.any_instance.stub(:save).and_return(false)
        put :update, :id => professional_question.id, :professional_question => {}
        assigns(:professional_question).should eq(professional_question)
      end

      it "re-renders the 'edit' template" do
        professional_question = ProfessionalQuestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProfessionalQuestion.any_instance.stub(:save).and_return(false)
        put :update, :id => professional_question.id, :professional_question => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested professional_question" do
      professional_question = ProfessionalQuestion.create! valid_attributes
      expect {
        delete :destroy, :id => professional_question.id
      }.to change(ProfessionalQuestion, :count).by(-1)
    end

    it "redirects to the professional_questions list" do
      professional_question = ProfessionalQuestion.create! valid_attributes
      delete :destroy, :id => professional_question.id
      response.should redirect_to(professional_questions_url)
    end
  end

end
