require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TagQRelationsController do

  # This should return the minimal set of attributes required to create a valid
  # TagQRelation. As you add validations to TagQRelation, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tag_q_relations as @tag_q_relations" do
      tag_q_relation = TagQRelation.create! valid_attributes
      get :index
      assigns(:tag_q_relations).should eq([tag_q_relation])
    end
  end

  describe "GET show" do
    it "assigns the requested tag_q_relation as @tag_q_relation" do
      tag_q_relation = TagQRelation.create! valid_attributes
      get :show, :id => tag_q_relation.id
      assigns(:tag_q_relation).should eq(tag_q_relation)
    end
  end

  describe "GET new" do
    it "assigns a new tag_q_relation as @tag_q_relation" do
      get :new
      assigns(:tag_q_relation).should be_a_new(TagQRelation)
    end
  end

  describe "GET edit" do
    it "assigns the requested tag_q_relation as @tag_q_relation" do
      tag_q_relation = TagQRelation.create! valid_attributes
      get :edit, :id => tag_q_relation.id
      assigns(:tag_q_relation).should eq(tag_q_relation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TagQRelation" do
        expect {
          post :create, :tag_q_relation => valid_attributes
        }.to change(TagQRelation, :count).by(1)
      end

      it "assigns a newly created tag_q_relation as @tag_q_relation" do
        post :create, :tag_q_relation => valid_attributes
        assigns(:tag_q_relation).should be_a(TagQRelation)
        assigns(:tag_q_relation).should be_persisted
      end

      it "redirects to the created tag_q_relation" do
        post :create, :tag_q_relation => valid_attributes
        response.should redirect_to(TagQRelation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tag_q_relation as @tag_q_relation" do
        # Trigger the behavior that occurs when invalid params are submitted
        TagQRelation.any_instance.stub(:save).and_return(false)
        post :create, :tag_q_relation => {}
        assigns(:tag_q_relation).should be_a_new(TagQRelation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TagQRelation.any_instance.stub(:save).and_return(false)
        post :create, :tag_q_relation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tag_q_relation" do
        tag_q_relation = TagQRelation.create! valid_attributes
        # Assuming there are no other tag_q_relations in the database, this
        # specifies that the TagQRelation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TagQRelation.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tag_q_relation.id, :tag_q_relation => {'these' => 'params'}
      end

      it "assigns the requested tag_q_relation as @tag_q_relation" do
        tag_q_relation = TagQRelation.create! valid_attributes
        put :update, :id => tag_q_relation.id, :tag_q_relation => valid_attributes
        assigns(:tag_q_relation).should eq(tag_q_relation)
      end

      it "redirects to the tag_q_relation" do
        tag_q_relation = TagQRelation.create! valid_attributes
        put :update, :id => tag_q_relation.id, :tag_q_relation => valid_attributes
        response.should redirect_to(tag_q_relation)
      end
    end

    describe "with invalid params" do
      it "assigns the tag_q_relation as @tag_q_relation" do
        tag_q_relation = TagQRelation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TagQRelation.any_instance.stub(:save).and_return(false)
        put :update, :id => tag_q_relation.id, :tag_q_relation => {}
        assigns(:tag_q_relation).should eq(tag_q_relation)
      end

      it "re-renders the 'edit' template" do
        tag_q_relation = TagQRelation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TagQRelation.any_instance.stub(:save).and_return(false)
        put :update, :id => tag_q_relation.id, :tag_q_relation => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tag_q_relation" do
      tag_q_relation = TagQRelation.create! valid_attributes
      expect {
        delete :destroy, :id => tag_q_relation.id
      }.to change(TagQRelation, :count).by(-1)
    end

    it "redirects to the tag_q_relations list" do
      tag_q_relation = TagQRelation.create! valid_attributes
      delete :destroy, :id => tag_q_relation.id
      response.should redirect_to(tag_q_relations_url)
    end
  end

end
