require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TagsClientQuestionsController do

  # This should return the minimal set of attributes required to create a valid
  # TagsClientQuestion. As you add validations to TagsClientQuestion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tags_client_questions as @tags_client_questions" do
      tags_client_question = TagsClientQuestion.create! valid_attributes
      get :index
      assigns(:tags_client_questions).should eq([tags_client_question])
    end
  end

  describe "GET show" do
    it "assigns the requested tags_client_question as @tags_client_question" do
      tags_client_question = TagsClientQuestion.create! valid_attributes
      get :show, :id => tags_client_question.id
      assigns(:tags_client_question).should eq(tags_client_question)
    end
  end

  describe "GET new" do
    it "assigns a new tags_client_question as @tags_client_question" do
      get :new
      assigns(:tags_client_question).should be_a_new(TagsClientQuestion)
    end
  end

  describe "GET edit" do
    it "assigns the requested tags_client_question as @tags_client_question" do
      tags_client_question = TagsClientQuestion.create! valid_attributes
      get :edit, :id => tags_client_question.id
      assigns(:tags_client_question).should eq(tags_client_question)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TagsClientQuestion" do
        expect {
          post :create, :tags_client_question => valid_attributes
        }.to change(TagsClientQuestion, :count).by(1)
      end

      it "assigns a newly created tags_client_question as @tags_client_question" do
        post :create, :tags_client_question => valid_attributes
        assigns(:tags_client_question).should be_a(TagsClientQuestion)
        assigns(:tags_client_question).should be_persisted
      end

      it "redirects to the created tags_client_question" do
        post :create, :tags_client_question => valid_attributes
        response.should redirect_to(TagsClientQuestion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tags_client_question as @tags_client_question" do
        # Trigger the behavior that occurs when invalid params are submitted
        TagsClientQuestion.any_instance.stub(:save).and_return(false)
        post :create, :tags_client_question => {}
        assigns(:tags_client_question).should be_a_new(TagsClientQuestion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TagsClientQuestion.any_instance.stub(:save).and_return(false)
        post :create, :tags_client_question => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tags_client_question" do
        tags_client_question = TagsClientQuestion.create! valid_attributes
        # Assuming there are no other tags_client_questions in the database, this
        # specifies that the TagsClientQuestion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TagsClientQuestion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tags_client_question.id, :tags_client_question => {'these' => 'params'}
      end

      it "assigns the requested tags_client_question as @tags_client_question" do
        tags_client_question = TagsClientQuestion.create! valid_attributes
        put :update, :id => tags_client_question.id, :tags_client_question => valid_attributes
        assigns(:tags_client_question).should eq(tags_client_question)
      end

      it "redirects to the tags_client_question" do
        tags_client_question = TagsClientQuestion.create! valid_attributes
        put :update, :id => tags_client_question.id, :tags_client_question => valid_attributes
        response.should redirect_to(tags_client_question)
      end
    end

    describe "with invalid params" do
      it "assigns the tags_client_question as @tags_client_question" do
        tags_client_question = TagsClientQuestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TagsClientQuestion.any_instance.stub(:save).and_return(false)
        put :update, :id => tags_client_question.id, :tags_client_question => {}
        assigns(:tags_client_question).should eq(tags_client_question)
      end

      it "re-renders the 'edit' template" do
        tags_client_question = TagsClientQuestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TagsClientQuestion.any_instance.stub(:save).and_return(false)
        put :update, :id => tags_client_question.id, :tags_client_question => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tags_client_question" do
      tags_client_question = TagsClientQuestion.create! valid_attributes
      expect {
        delete :destroy, :id => tags_client_question.id
      }.to change(TagsClientQuestion, :count).by(-1)
    end

    it "redirects to the tags_client_questions list" do
      tags_client_question = TagsClientQuestion.create! valid_attributes
      delete :destroy, :id => tags_client_question.id
      response.should redirect_to(tags_client_questions_url)
    end
  end

end
